routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Authentication routes
Auth::routes();
Route::get('logout', 'Auth\LoginController@logout');

// Resource route for managing item types
Route::resource('item_types', 'TypesController');

// Resource route for managing vendors
Route::resource('item_vendors', 'VendorsController');

// Resource route for managing items
Route::resource('items', 'ItemsController');

// Home route
Route::get('/home', 'DashboardController@index');
Route::get('/', 'DashboardController@index');

// Routes for getting data about statistics
Route::get('/stats/item_percentages', 'DashboardController@getItemsPercentages');

// Routes for backups and restore functionality
Route::get('/backups', 'BackupsController@index');
Route::post('/backup', 'BackupsController@backup');
Route::post('/restore', 'BackupsController@restore');

// Users Routes
Route::resource('users', 'UsersController');
Route::get('my_account', 'UsersController@show');
Route::get('activate', 'UsersController@activate');
Route::post('activate', 'UsersController@updatePassword');

app/Models/Item.php
<?php

namespace App\Models;

use URL;
use Storage;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    protected $guarded = [];

    /**
     * Create a relationship between an item and its type
     * 
     * @return App\Models\Type
     */
    public function type()
    {
    	return $this->belongsTo(Type::class, 'type_id');
    }

    /**
     * Create a relationship between an item and its vendor
     * 
     * @return App\Models\Vendor
     */
    public function vendor()
    {
    	return $this->belongsTo(Vendor::class, 'vendor_id');
    }

    /**
     * Mutator for returning full server path to uploaded item images
     * 
     * @param  string $value The image path as stored in the DB
     * @return string The mutated value
     */
    public function getImageUrlAttribute($value)
    {
        return $value ? URL::asset(Storage::url($value)) : null;
    }
}

app/Models/Vendor.php
<?php

namespace App\Models;

use URL;
use Storage;
use Illuminate\Database\Eloquent\Model;

class Vendor extends Model
{
    protected $guarded = [];

    /**
     * Create a relationship between a vendor and the items 
     * sold by her
     * 
     * @return App\Models\Items The items
     */
    public function items()
    {
    	return $this->hasMany(Item::class, 'vendor_id');
    }

    /**
     * Mutator for returning full server path to uploaded logo images
     * 
     * @param  string $value The logo path as stored in the DB
     * @return string The mutated value
     */
    public function getLogoUrlAttribute($value)
    {
        return $value ? URL::asset(Storage::url($value)) : null;
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\Vendor;
use App\Models\Item;
use App\Models\User;

use Auth;
use Illuminate\Http\Request;
use App\Services\StatisticsService;

class DashboardController extends Controller
{
    /**
     * Create a new instance of the DashboardController
     * 
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('activated');
    }

    /**
     * Show the dashboard page
     * 
     * @return Illuminate\Http\Response
     */
    public function index()
    {
        // If logged in user is not an admin,
        // redirect to items page
        if (Auth::user()->isUser()) {
            return redirect('/items');
        }

    	$users = User::all();
    	$vendors = Vendor::all();
    	$items = Item::all();
        $latest_items = Item::orderBy('created_at', 'DESC')->take(5)->get();
    	$average_price = StatisticsService::getAveragePrice();
    	return view('dashboard.index', compact('vendors', 'items', 'users', 'average_price', 'latest_items'));
    }

    /**
     * Return data for drawing graph on dashboard
     * 
     * @return Illuminate\Http\Response
     */
    public function getItemsPercentages()
    {
    	return StatisticsService::getItemsByTypes();
    }
}

resources/views/dashboard/index.blade.php
@extends('layouts.app')

@section('title')
	Dashboard
@endsection

@section('page_title')
    Dashboard
@endsection

@section('content') 
	<div class="row">
	    <div class="col-md-12 col-lg-12 col-sm-12">
		    <div class="row tile_count">
		        <div class="col-md-3 col-sm-4 col-xs-6 tile_stats_count">
		            <span class="count_top"><i class="fa fa-institution"></i> Vendors</span>
		            <div class="count">{{ count($vendors) }}</div>
		        </div>

		        <div class="col-md-3 col-sm-4 col-xs-6 tile_stats_count">
		            <span class="count_top"><i class="fa fa-gift"></i> Items</span>
		            <div class="count">{{ count($items) }}</div>
		        </div>

		        <div class="col-md-3 col-sm-5 col-xs-6 tile_stats_count">
		            <span class="count_top"><i class="fa fa-money"></i> Average Price</span>
		            <div class="count">${{ $average_price }}</div>
		        </div>

		        <div class="col-md-3 col-sm-5 col-xs-6 tile_stats_count">
		            <span class="count_top"><i class="fa fa-user"></i> Users</span>
		            <div class="count">{{ count($users) }}</div>
		        </div>
		    </div> 
        </div>
	</div>

	<div class="row">
        <div class="col-md-12 col-lg-12 col-sm-6 col-xs-6">
            <div class="dashboard_graph">
                <div class="row x_title">
                    <div class="col-md-12 col-lg-12 col-sm-6">
                        <h3>Item Types</h3>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div id="item-percentages" class="demo-placeholder" style="height: 400px"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-6 col-xs-6">
            <div class="row x_title">
                <div class="col-md-12 col-lg-12 col-sm-6">
                    <h3>Latest Items</h3>
                </div>
            </div>

            <table class="table table-bordered">
                <tr>
                    <td colspan="2">Item</td>
                    <td colspan="2">Vendor</td>
                    <td>Price</td>
                    <td>Tags</td>
                </tr>

                @foreach($latest_items as $item)
                <tr>
                    <td><img src="{{ $item->image_url }}" class="vendor-logo img img-responsive"></td>
                    <td>{{ $item->name }}</td>
                    <td><img src="{{ $item->vendor->logo_url }}" class="vendor-logo img img-responsive"></td>
                    <td>{{ $item->vendor->name }}</td>
                    <td>${{ $item->price }}</td>
                    <td>{{ $item->tags }}</td>
                </tr>
                @endforeach
            </table>
        </div>
    </div>
@endsection

@section('scripts')
<script src="/js/dashboard.js"></script>
@endsection